# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'gui.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1119, 858)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.bg = QtWidgets.QLabel(self.centralwidget)
        self.bg.setGeometry(QtCore.QRect(-110, -70, 1351, 1011))
        self.bg.setStyleSheet("background-color: rgb(0, 0, 0);")
        self.bg.setText("")
        self.bg.setObjectName("bg")
        self.initial = QtWidgets.QLabel(self.centralwidget)
        self.initial.setGeometry(QtCore.QRect(10, 10, 491, 321))
        self.initial.setStyleSheet("\n"
"")
        self.initial.setText("")
        self.initial.setScaledContents(True)
        self.initial.setObjectName("initial")
       
        self.start = QtWidgets.QPushButton(self.centralwidget)
        self.start.setGeometry(QtCore.QRect(730, 760, 171, 71))
        self.start.setStyleSheet("background-image: url(:/newPrefix/bt.jpg);\n"
"font: 16pt \"MS Shell Dlg 2\";\n"
"color: rgb(0, 255, 255);")
        self.start.setObjectName("start")
        self.exit = QtWidgets.QPushButton(self.centralwidget)
        self.exit.setGeometry(QtCore.QRect(910, 760, 171, 71))
        self.exit.setStyleSheet("background-image: url(:/newPrefix/bt.jpg);\n"
"font: 16pt \"MS Shell Dlg 2\";\n"
"color: rgb(0, 255, 255);")
        self.exit.setObjectName("exit")
        self.gif1 = QtWidgets.QLabel(self.centralwidget)
        self.gif1.setGeometry(QtCore.QRect(580, 310, 531, 441))
        self.gif1.setStyleSheet("")
        self.gif1.setText("")
        
        self.gif1.setScaledContents(True)
        self.gif1.setObjectName("gif1")
        self.terminal = QtWidgets.QLabel(self.centralwidget)
        self.terminal.setGeometry(QtCore.QRect(10, 340, 561, 511))
        self.terminal.setStyleSheet("background-color: rgb(0, 0, 0);\n"
"border: 2px solid white;\n"
"")
        self.terminal.setText("")
        self.terminal.setObjectName("terminal")
        self.time = QtWidgets.QLabel(self.centralwidget)
        self.time.setGeometry(QtCore.QRect(510, 10, 271, 91))
        self.time.setStyleSheet("background-color: rgb(0, 0, 0);\n"
"border: 2px solid white;\n"
"")
        self.time.setText("")
        self.time.setObjectName("time")
        self.b1 = QtWidgets.QPushButton(self.centralwidget)
        self.b1.setGeometry(QtCore.QRect(800, 20, 131, 71))
        self.b1.setStyleSheet("background-image: url(:/newPrefix/bt.jpg);\n"
"font: 16pt \"MS Shell Dlg 2\";\n"
"color: rgb(0, 255, 255);")
        self.b1.setObjectName("b1")
        self.b2 = QtWidgets.QPushButton(self.centralwidget)
        self.b2.setGeometry(QtCore.QRect(950, 20, 131, 71))
        self.b2.setStyleSheet("background-image: url(:/newPrefix/bt.jpg);\n"
"font: 16pt \"MS Shell Dlg 2\";\n"
"color: rgb(0, 255, 255);")
        self.b2.setObjectName("b2")
        self.b4 = QtWidgets.QPushButton(self.centralwidget)
        self.b4.setGeometry(QtCore.QRect(950, 130, 131, 71))
        self.b4.setStyleSheet("background-image: url(:/newPrefix/bt.jpg);\n"
"font: 16pt \"MS Shell Dlg 2\";\n"
"color: rgb(0, 255, 255);")
        self.b4.setObjectName("b4")
        self.b3 = QtWidgets.QPushButton(self.centralwidget)
        self.b3.setGeometry(QtCore.QRect(800, 130, 131, 71))
        self.b3.setStyleSheet("background-image: url(:/newPrefix/bt.jpg);\n"
"font: 16pt \"MS Shell Dlg 2\";\n"
"color: rgb(0, 255, 255);")
        self.b3.setObjectName("b3")
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.start.setText(_translate("MainWindow", "START"))
        self.exit.setText(_translate("MainWindow", "EXIT"))
        self.b1.setText(_translate("MainWindow", "b1"))
        self.b2.setText(_translate("MainWindow", "b2"))
        self.b4.setText(_translate("MainWindow", "b4"))
        self.b3.setText(_translate("MainWindow", "b3"))
import buttonbackground


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
